# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('vehicle_type', models.CharField(choices=[('car', 'سواری'), ('autocar', 'ون'), ('carrier', 'باری'), ('motorcycle', 'موتورسیکلت')], max_length=20)),
                ('vehicle_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_models', to='bimebazar.VehicleBrand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
